export const ROLES = {
  STUDENT: 'student',
  FACULTY: 'faculty',
  COUNCIL: 'council',
  HOD: 'hod',
  DEAN: 'dean',
};

export const SUB_ROLES = {
  COMMITTEE_HEAD: 'committee_head',
  CLASS_REP: 'class_rep',
  SPORTS_SECRETARY: 'sports_secretary',
  TIMETABLE_COORD: 'timetable_coord',
};

// Which roles can raise event requests
export const EVENT_REQUEST_SUBROLES = [
  SUB_ROLES.COMMITTEE_HEAD,
  SUB_ROLES.CLASS_REP,
  SUB_ROLES.SPORTS_SECRETARY,
];

// Permission map: resource -> allowed roles
export const PERMISSIONS = {
  TIMETABLE_UPLOAD: [ROLES.FACULTY],       // + subRole check: timetable_coord
  TIMETABLE_APPROVE: [ROLES.HOD],
  TIMETABLE_VIEW: [ROLES.STUDENT, ROLES.FACULTY, ROLES.HOD, ROLES.DEAN],

  ATTENDANCE_MARK: [ROLES.FACULTY],
  ATTENDANCE_VIEW_OWN: [ROLES.STUDENT],
  ATTENDANCE_VIEW_DEPT: [ROLES.HOD, ROLES.DEAN],
  ATTENDANCE_VIEW_ALL: [ROLES.FACULTY],    // for their own subjects

  SYLLABUS_UPDATE: [ROLES.FACULTY],
  SYLLABUS_VIEW: [ROLES.STUDENT, ROLES.FACULTY, ROLES.HOD, ROLES.DEAN],
  SYLLABUS_COORD_BOARD: [ROLES.FACULTY, ROLES.HOD],

  EVENT_REQUEST_CREATE: [ROLES.STUDENT],   // + subRole check
  EVENT_REQUEST_L1_APPROVE: [ROLES.COUNCIL],
  EVENT_REQUEST_L2_APPROVE: [ROLES.HOD],
  EVENT_CALENDAR_WRITE: [ROLES.COUNCIL],
  EVENT_CALENDAR_READ: [ROLES.STUDENT, ROLES.FACULTY, ROLES.COUNCIL, ROLES.HOD, ROLES.DEAN],

  ISSUE_REPORT: [ROLES.STUDENT],
  ISSUE_RESOLVE: [ROLES.FACULTY, ROLES.HOD],
  ISSUE_REASSIGN: [ROLES.HOD],

  ANALYTICS_DEPT: [ROLES.HOD],
  ANALYTICS_COLLEGE: [ROLES.DEAN],

  SUBROLE_ASSIGN: [ROLES.COUNCIL, ROLES.HOD],
  ANNOUNCEMENTS_PUBLISH: [ROLES.COUNCIL, ROLES.FACULTY, ROLES.HOD],

  CHATBOT_USE: [ROLES.STUDENT],
  CHATBOT_ESCALATION_MANAGE: [ROLES.COUNCIL, ROLES.HOD],
};
