import PDFDocument from 'pdfkit';

export function generateEventCertificate(event, requestedBy) {
  return new Promise((resolve, reject) => {
    try {
      const doc = new PDFDocument({ size: 'A4', margin: 50 });
      const buffers = [];

      doc.on('data', buffers.push.bind(buffers));
      doc.on('end', () => {
        const pdfData = Buffer.concat(buffers);
        const base64Str = `data:application/pdf;base64,${pdfData.toString('base64')}`;
        resolve(base64Str);
      });
      doc.on('error', reject);

      // Certificate content
      doc.fontSize(24).text('Event Approval Certificate', { align: 'center' });
      doc.moveDown(2);

      doc.fontSize(14).text(`This is to certify that the event "${event.title}" has been fully approved by the authorities.`);
      doc.moveDown(1);
      
      doc.fontSize(12);
      doc.text(`Requested By: ${requestedBy.name || 'Student'}`);
      doc.text(`Venue: ${event.venue}`);
      doc.text(`Start Time: ${new Date(event.startTime).toLocaleString()}`);
      doc.text(`End Time: ${new Date(event.endTime).toLocaleString()}`);
      doc.text(`Expected Attendance: ${event.expectedAttendance}`);
      doc.moveDown(2);

      doc.text('Approval Chain:');
      if (event.chain && event.chain.length > 0) {
        event.chain.forEach(step => {
          doc.text(`- ${step.role.toUpperCase()}: ${step.status.toUpperCase()} on ${new Date(step.timestamp).toLocaleString()}`);
        });
      }

      doc.moveDown(3);
      doc.fontSize(10).text('Generated by Aether Mobile Workflow Engine', { align: 'center', color: 'gray' });

      doc.end();
    } catch (err) {
      reject(err);
    }
  });
}
